# Generated by Django 3.0.6 on 2020-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('slug', models.SlugField()),
                ('subtitle', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=2000)),
                ('ISBN', models.CharField(max_length=13)),
            ],
        ),
    ]
