# Generated by Django 3.0.6 on 2020-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('title',), 'verbose_name': 'Books', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='books',
            name='slug',
            field=models.SlugField(max_length=4000),
        ),
    ]
